# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy
theme_mode: dark
name : &name "Dhruv Tiwari" # &name is a YAML anchor which can be *referenced later
teaser : /assets/images/dhruv_profilepic.png # path of fallback teaser image, e.g. "/assets/images/500x300.png"
baseurl: ''
lang: en
timezone: America/New_York
title: DRamaT-ic
tagline: Audion • AWS • Full Stack  
url: 'https://dhruvrt.github.io'
github:
  username: dhruvrt
twitter:
  username: dhruv7

social:
  name: *name
  email: dhruv@piddlecast.com
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/_dhruv7 # change to your twitter homepage
    - https://github.com/daydh7 # change to your github homepage
    - https://www.linkedin.com/in/dhruvtiwari7/

# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/dhruv_profilepic.png"
  bio              : "Just another *boring*, *tattooed*, *time traveling*, *designer*."
  location         : "Buffalo, NY"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_dhruv7"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/daydh7"
    - label: "LinkedIn"
      icon : "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/dhruvtiwari7/"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_dhruv7"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/daydh7"
    - label: "LinkedIn"
      icon : "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/dhruvtiwari7/"

# the avatar on sidebar, support local or CORS resources
avatar: /assets/images/dhruv_profilepic.png
# boolean type, the global switch for ToC in posts.
toc: true


# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
